package com.guicedee.vertx.auth.htdigest;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares htdigest-file-based authentication configuration.
 * Place on a class or {@code package-info.java} to opt-in.
 * <p>
 * Uses the Apache htdigest file format (generated by the {@code htdigest} tool).
 * The file is loaded once at startup — no live reloading.
 * This is authentication only (HTTP Digest Auth); htdigest provides no authorization.
 * <p>
 * Nonce generation and counters must be handled outside this provider.
 * {@code auth-int} qop is not supported.
 *
 * <h3>Usage</h3>
 * <pre>
 * &#64;HtdigestAuthOptions(path = ".htdigest")
 * package com.example.auth;
 * </pre>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.PACKAGE})
public @interface HtdigestAuthOptions
{
    /**
     * @return Path to the .htdigest file. Default {@code ".htdigest"} (project root).
     */
    String path() default ".htdigest";
}

