package com.guicedee.vertx.auth.htpasswd;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares htpasswd-file-based authentication configuration.
 * Place on a class or {@code package-info.java} to opt-in.
 * <p>
 * Uses the Apache htpasswd file format (generated by the {@code htpasswd} tool).
 * The file is loaded once at startup — no live reloading.
 * This is authentication only; htpasswd provides no authorization.
 * <p>
 * All string attributes support {@code ${ENV_VAR}} placeholders and can be overridden
 * via environment variables with the {@code VERTX_AUTH_HTPASSWD_} prefix.
 *
 * <h3>Usage</h3>
 * <pre>
 * &#64;HtpasswdAuthOptions(path = ".htpasswd")
 * package com.example.auth;
 * </pre>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.PACKAGE})
public @interface HtpasswdAuthOptions
{
    /**
     * @return Path to the htpasswd file. Default {@code ".htpasswd"} (project root).
     */
    String path() default ".htpasswd";

    /**
     * @return Whether plain-text passwords are enabled. Default {@code false}.
     *         <strong>Only for development — never in production.</strong>
     */
    boolean plainTextEnabled() default false;
}

