name: Guiced Vert.x Injection
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
jobs:
  GuicedInjection:
    uses: GuicedEE/Workflows/.github/workflows/projects.yml@master
    with:
      baseDir: ''
      name: 'Guiced Vert.x Injection'
      sonarProjectName: 'GuicedEE_Guiced-Vert.x'
      sonarOrganization: 'guicedee'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit